(function(){
  const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const origin='https://jburris04.github.io/The-Beacon/';
  function relate(edition){return edition.stories.map((s,i)=>({...s,related:edition.stories.filter((_,j)=>j!==i).sort((a,b)=>(b.section===s.section)-(a.section===s.section)).slice(0,3).map(x=>x.slug)}))}
  function articleShell(s){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#102d42"><title>${esc(s.headline)} — The Beacon</title><meta name="description" content="${esc(s.standfirst)}"><link rel="stylesheet" href="../../assets/styles.css"></head><body data-view="article" data-slug="${esc(s.slug)}" data-base="../../"><a class="skip-link" href="#main">Skip to content</a><div class="topline"></div><header class="masthead"><div class="masthead-inner"><nav class="site-nav"><a href="../../index.html">Home</a><a href="../../archive/index.html">Editions</a><a href="../../about/index.html">About</a></nav><a class="wordmark" href="../../index.html">THE BEACON<small>CLARITY WITHOUT THE NOISE</small></a><div class="nav-actions"><button class="theme-toggle" aria-label="Switch color theme"></button><a class="subscribe-link" href="../../subscribe/index.html">Subscribe</a><button class="menu-button">Menu</button></div></div></header><main class="article-page shell" id="main"><article><a class="back-link" id="article-back"></a><header class="article-header"><p class="eyebrow" id="article-section"></p><h1 id="article-headline">Loading story…</h1><p class="standfirst" id="article-standfirst"></p><p class="byline" id="article-byline"></p></header><div class="article-body" id="article-body"><p id="page-status"></p></div></article><aside class="article-aside"><p class="eyebrow">This Edition</p><h2 id="article-theme"></h2><a class="text-link" id="article-theme-link">Read the full edition →</a></aside></main><script src="../../assets/site.js"></script></body></html>`}
  function editionShell(d){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Edition ${esc(d.edition)}: ${esc(d.theme)} — The Beacon</title><meta name="description" content="${esc(d.summary)}"><link rel="stylesheet" href="../../assets/styles.css"></head><body data-view="edition" data-edition="${esc(d.edition)}" data-base="../../"><div class="topline"></div><header class="masthead"><div class="masthead-inner"><nav class="site-nav"><a href="../../index.html">Home</a><a href="../../archive/index.html">Editions</a><a href="../../about/index.html">About</a></nav><a class="wordmark" href="../../index.html">THE BEACON<small>CLARITY WITHOUT THE NOISE</small></a><div class="nav-actions"><button class="theme-toggle"></button><a class="subscribe-link" href="../../subscribe/index.html">Subscribe</a><button class="menu-button">Menu</button></div></div></header><main><header class="edition-hero shell"><p class="eyebrow"><span id="edition-number"></span> · <span id="edition-date"></span></p><h1 id="edition-theme">Loading…</h1><p class="hero-summary" id="edition-summary"></p><div class="edition-meta"><span id="reading-time"></span><button class="print-button">Print this edition</button></div></header><section class="editor-note shell"><p class="eyebrow">From the Editorial Desk</p><h2>Good morning.</h2><p id="editor-note"></p></section><section class="edition-stories shell" id="edition-stories"></section><div id="edition-radar"></div></main><script src="../../assets/site.js"></script></body></html>`}
  function rss(editions,latest){return `<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>The Beacon</title><link>${origin}</link><description>Clarity without the noise.</description>${editions.map(e=>`<item><title>${esc(e.theme)}</title><link>${origin}edition/${e.edition}/</link><guid>${origin}edition/${e.edition}/</guid><pubDate>${new Date(`${e.date}T12:00:00Z`).toUTCString()}</pubDate><description>${esc(e.summary)}</description></item>`).join('')}</channel></rss>`}
  function sitemap(editions,stories,previous=''){const urls=new Set([...previous.matchAll(/<loc>(.*?)<\/loc>/g)].map(m=>m[1]));['','archive/','about/','subscribe/'].forEach(p=>urls.add(origin+p));editions.forEach(e=>urls.add(`${origin}edition/${e.edition}/`));stories.forEach(s=>urls.add(`${origin}article/${s.slug}/`));return `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${[...urls].map(u=>`<url><loc>${esc(u)}</loc></url>`).join('')}</urlset>`}
  async function build(edition,existing=[],existingSearch=[],existingRelated={},existingSitemap=''){
    const d=structuredClone(edition);d.status='published';d.published_at=new Date().toISOString();d.stories=relate(d);
    const summary={edition:d.edition,date:d.date,date_display:d.date_display,theme:d.theme,summary:d.summary,reading_time:d.reading_time,status:'published'};
    const editions=[summary,...existing.filter(x=>x.edition!==d.edition)].sort((a,b)=>b.date.localeCompare(a.date));
    const search=[...d.stories.map(s=>({edition:d.edition,date:d.date,slug:s.slug,section:s.section,headline:s.headline,standfirst:s.standfirst,url:`article/${s.slug}/index.html`})),...existingSearch.filter(s=>s.edition!==d.edition)];
    const related={...existingRelated,...Object.fromEntries(d.stories.map(s=>[s.slug,s.related]))};
    const files={[`content/editions/edition-${d.edition}.json`]:JSON.stringify(d,null,2)+'\n','content/editions/index.json':JSON.stringify(editions,null,2)+'\n','content/search-index.json':JSON.stringify(search,null,2)+'\n','content/related.json':JSON.stringify(related,null,2)+'\n',[`edition/${d.edition}/index.html`]:editionShell(d),'rss.xml':rss(editions,d),'sitemap.xml':sitemap(editions,d.stories,existingSitemap)};
    d.stories.forEach(s=>files[`article/${s.slug}/index.html`]=articleShell(s));
    for(const p of ['index.html','archive/index.html'])files[p]=await fetch(`../${p}`).then(r=>r.text());
    return {files,edition:d,links:{homepage:origin,edition:`${origin}edition/${d.edition}/`,archive:`${origin}archive/`,articles:d.stories.map(s=>({title:s.headline,url:`${origin}article/${s.slug}/`}))}};
  }
  window.BeaconGenerator={build,relate};
})();
