const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const form=$('#edition-form'), storiesEl=$('#story-editors'), radarEl=$('#radar-editors');
let model;
const blankStory=()=>({slug:'new-story',section:'News',headline:'Untitled story',standfirst:'What readers need to know.',paragraphs:['Begin the story here.'],pull_quote:'',bottom_line:'',provider_impact:'',patient_impact:''});
const blankEdition=()=>({schema_version:1,edition:'003',date:new Date().toISOString().slice(0,10),date_display:'',theme:'A New Edition',summary:'The connecting idea behind today’s essential stories.',editor_note:'Good morning. Here is what we are seeing today.',reading_time:'10 minutes',stories:[blankStory()],radar:[{title:'A developing story',detail:'What the newsroom is watching next.'}]});
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slugify=s=>String(s).toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function sync(){
  const data=Object.fromEntries(new FormData(form)); Object.assign(model,data);
  model.date_display=new Intl.DateTimeFormat('en-US',{weekday:'long',year:'numeric',month:'long',day:'numeric'}).format(new Date(`${model.date}T12:00:00`));
  model.stories=$$('.story-editor',storiesEl).map(el=>{const o={}; $$('[data-field]',el).forEach(f=>o[f.dataset.field]=f.dataset.field==='paragraphs'?f.value.split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean):f.value.trim());return o});
  model.radar=$$('.radar-editor',radarEl).map(el=>{const o={}; $$('[data-field]',el).forEach(f=>o[f.dataset.field]=f.value.trim());return o});
  $('#editor-heading').textContent=`Edition ${model.edition||'—'}`;
}
function addEditor(type,item){
  const template=$(`#${type}-template`), node=template.content.firstElementChild.cloneNode(true), target=type==='story'?storiesEl:radarEl;
  $$('[data-field]',node).forEach(f=>{let v=item[f.dataset.field]??'';if(Array.isArray(v))v=v.join('\n\n');f.value=v;});
  node.addEventListener('click',e=>{const action=e.target.dataset.action;if(!action)return;if(action==='remove')node.remove();if(action==='up'&&node.previousElementSibling)target.insertBefore(node,node.previousElementSibling);if(action==='down'&&node.nextElementSibling)target.insertBefore(node.nextElementSibling,node);sync();preview();});
  target.append(node);
}
function render(){
  ['edition','date','theme','summary','editor_note','reading_time'].forEach(k=>form.elements[k].value=model[k]||'');
  storiesEl.replaceChildren(); model.stories.forEach(s=>addEditor('story',s)); radarEl.replaceChildren(); model.radar.forEach(r=>addEditor('radar',r));
  sync(); renderDrafts(); preview();
}
function drafts(){return Object.keys(localStorage).filter(k=>k.startsWith('beacon-draft-')).map(k=>JSON.parse(localStorage.getItem(k))).sort((a,b)=>b.date.localeCompare(a.date));}
function renderDrafts(){const list=$('#draft-list'),ds=drafts();list.innerHTML=ds.length?'':'<p>No drafts saved yet.</p>';ds.forEach(d=>{const b=document.createElement('button');b.className='draft-button';b.innerHTML=`<strong>Edition ${esc(d.edition)}</strong><span>${esc(d.theme)}</span>`;b.onclick=()=>{model=structuredClone(d);render()};list.append(b)});}
function save(){sync();localStorage.setItem(`beacon-draft-${model.edition}`,JSON.stringify(model));$('#save-status').textContent=`Saved at ${new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}`;renderDrafts();}
function previewHtml(d){
  const impacts=s=>(s.provider_impact||s.patient_impact)?`<div class="imp"><div><b>For Providers</b><p>${esc(s.provider_impact)}</p></div><div><b>For Patients</b><p>${esc(s.patient_impact)}</p></div></div>`:'';
  return `<!doctype html><meta name="viewport" content="width=device-width"><style>:root{--n:#102d42;--p:#f4efe5;--g:#b68a42}*{box-sizing:border-box}body{margin:0;color:#18242c;font:16px/1.6 Georgia;background:#fffdf8}header{border-top:6px solid var(--n);padding:28px 7%;border-bottom:1px solid #ddd}.brand{font:bold 20px Arial;letter-spacing:.15em}.eye{font:bold 10px Arial;letter-spacing:.16em;text-transform:uppercase;color:var(--g)}h1{font-size:clamp(46px,8vw,78px);line-height:.95;color:var(--n);font-weight:500;margin:35px 0 18px}main{padding:20px 7%}.note{background:var(--p);padding:24px;margin:25px 0}.story{padding:38px 0;border-top:1px solid #d8d0c2}.story h2{font-size:36px;line-height:1.05;color:var(--n);margin:8px 0}.story blockquote{font-size:27px;border-block:1px solid var(--g);padding:20px 0}.bottom{background:var(--p);border-left:5px solid var(--g);padding:20px;margin-top:25px}.imp{display:grid;grid-template-columns:1fr 1fr;gap:12px}.imp div{padding:18px;background:var(--p)}.radar{background:var(--n);color:white;padding:35px 7%}.radar article{border-top:1px solid #ffffff44;padding:12px 0}@media(max-width:600px){.imp{grid-template-columns:1fr}}</style><header><div class="brand">THE BEACON</div><p class="eye">Edition ${esc(d.edition)} · ${esc(d.date_display)}</p><h1>${esc(d.theme)}</h1><p>${esc(d.summary)}</p></header><main><section class="note"><p class="eye">From the Editorial Desk</p><p>${esc(d.editor_note)}</p></section>${d.stories.map(s=>`<article class="story"><p class="eye">${esc(s.section)}</p><h2>${esc(s.headline)}</h2><p>${esc(s.standfirst)}</p>${s.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}${s.pull_quote?`<blockquote>${esc(s.pull_quote)}</blockquote>`:''}${impacts(s)}${s.bottom_line?`<div class="bottom"><p class="eye">The Bottom Line</p><p>${esc(s.bottom_line)}</p></div>`:''}</article>`).join('')}</main><section class="radar"><p class="eye">Already on Our Radar</p><h2>What we’re watching next</h2>${d.radar.map(r=>`<article><b>${esc(r.title)}</b><p>${esc(r.detail)}</p></article>`).join('')}</section>`;
}
function preview(){sync();$('#preview').srcdoc=previewHtml(model);}
function download(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function exportJson(){sync();download(`edition-${model.edition}.json`,new Blob([JSON.stringify(model,null,2)+'\n'],{type:'application/json'}));}
function articleShell(slug){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Story — The Beacon</title><meta name="description" content="A story from The Beacon."><link rel="stylesheet" href="../../assets/styles.css"></head><body data-view="article" data-slug="${esc(slug)}" data-base="../../"><div class="topline"></div><header class="masthead"><div class="masthead-inner"><nav class="site-nav"><a href="../../index.html">Home</a><a href="../../archive/index.html">Editions</a><a href="../../about/index.html">About</a></nav><a class="wordmark" href="../../index.html">THE BEACON<small>CLARITY WITHOUT THE NOISE</small></a><div class="nav-actions"><button class="theme-toggle" aria-label="Switch color theme"></button><a class="subscribe-link" href="../../subscribe/index.html">Subscribe</a><button class="menu-button">Menu</button></div></div></header><main class="article-page shell"><article><a class="back-link" id="article-back"></a><header class="article-header"><p class="eyebrow" id="article-section"></p><h1 id="article-headline">Loading story…</h1><p class="standfirst" id="article-standfirst"></p><p class="byline" id="article-byline"></p></header><div class="article-body" id="article-body"><p id="page-status"></p></div></article><aside class="article-aside"><p class="eyebrow">This Edition</p><h2 id="article-theme"></h2><a class="text-link" id="article-theme-link">Read the full edition →</a></aside></main><script src="../../assets/site.js"></script></body></html>`;}
function editionShell(n){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Edition ${esc(n)} — The Beacon</title><meta name="description" content="A complete edition of The Beacon."><link rel="stylesheet" href="../../assets/styles.css"></head><body data-view="edition" data-edition="${esc(n)}" data-base="../../"><div class="topline"></div><header class="masthead"><div class="masthead-inner"><nav class="site-nav"><a href="../../index.html">Home</a><a href="../../archive/index.html">Editions</a><a href="../../about/index.html">About</a></nav><a class="wordmark" href="../../index.html">THE BEACON<small>CLARITY WITHOUT THE NOISE</small></a><div class="nav-actions"><button class="theme-toggle"></button><a class="subscribe-link" href="../../subscribe/index.html">Subscribe</a><button class="menu-button">Menu</button></div></div></header><main><header class="edition-hero shell"><p class="eyebrow"><span id="edition-number"></span> · <span id="edition-date"></span></p><h1 id="edition-theme">Loading…</h1><p class="hero-summary" id="edition-summary"></p><div class="edition-meta"><span id="reading-time"></span><button class="print-button">Print this edition</button></div></header><section class="editor-note shell"><p class="eyebrow">From the Editorial Desk</p><h2>Good morning.</h2><p id="editor-note"></p></section><section class="edition-stories shell" id="edition-stories"><p id="page-status"></p></section><div id="edition-radar"></div></main><script src="../../assets/site.js"></script></body></html>`;}
function crc32(bytes){let c=-1;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^-1)>>>0}
function u16(n){return[n&255,(n>>>8)&255]}function u32(n){return[n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]}
function zip(files){const enc=new TextEncoder(),local=[],central=[];let offset=0;Object.entries(files).forEach(([name,text])=>{const n=enc.encode(name),d=enc.encode(text),crc=crc32(d),lh=new Uint8Array([...u32(0x04034b50),...u16(20),0,0,0,0,0,0,0,0,...u32(crc),...u32(d.length),...u32(d.length),...u16(n.length),0,0,...n]);local.push(lh,d);const ch=new Uint8Array([...u32(0x02014b50),...u16(20),...u16(20),0,0,0,0,0,0,0,0,...u32(crc),...u32(d.length),...u32(d.length),...u16(n.length),0,0,0,0,0,0,0,0,0,0,...u32(offset),...n]);central.push(ch);offset+=lh.length+d.length});const csize=central.reduce((n,a)=>n+a.length,0),count=Object.keys(files).length,end=new Uint8Array([...u32(0x06054b50),0,0,0,0,...u16(count),...u16(count),...u32(csize),...u32(offset),0,0]);return new Blob([...local,...central,end],{type:'application/zip'})}
async function publishPackage(){sync();const current=await fetch('../content/editions/index.json').then(r=>r.json()).catch(()=>[]),summary={edition:model.edition,date:model.date,date_display:model.date_display,theme:model.theme,summary:model.summary,reading_time:model.reading_time},index=[summary,...current.filter(x=>x.edition!==model.edition)].sort((a,b)=>b.date.localeCompare(a.date));const files={[`content/editions/edition-${model.edition}.json`]:JSON.stringify(model,null,2)+'\n','content/editions/index.json':JSON.stringify(index,null,2)+'\n',[`edition/${model.edition}/index.html`]:editionShell(model.edition),'READ-ME-FIRST.txt':`BEACON PUBLISH PACKAGE\n\nCopy the content, edition, and article folders into the root of The-Beacon in GitHub Desktop. Replace matching files, commit, and Push origin. Do not copy this instruction file.\n`};model.stories.forEach(s=>files[`article/${s.slug||slugify(s.headline)}/index.html`]=articleShell(s.slug||slugify(s.headline)));download(`beacon-edition-${model.edition}-publish.zip`,zip(files));$('#save-status').textContent='Publish package generated.';}
form.addEventListener('input',()=>{clearTimeout(window.previewTimer);window.previewTimer=setTimeout(preview,250)});$('#save-draft').onclick=save;$('#export-json').onclick=exportJson;$('#publish-package').onclick=publishPackage;$('#refresh-preview').onclick=preview;$('#new-edition').onclick=()=>{model=blankEdition();render()};$('#add-story').onclick=()=>{addEditor('story',blankStory());sync();preview()};$('#add-radar').onclick=()=>{addEditor('radar',{title:'New Radar item',detail:''});sync();preview()};
fetch('../content/editions/edition-002.json').then(r=>r.json()).then(d=>{model=d;render()}).catch(()=>{model=blankEdition();render()});
