const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];const form=$('#edition-form'),storiesEl=$('#story-editors'),radarEl=$('#radar-editors');let model,status='draft',timer,lastErrors=[];
const blankStory=()=>({slug:'new-story',section:'News',category:'News',headline:'Untitled story',standfirst:'What readers need to know.',body:['Begin the story here.'],sources:[],pull_quote:'',bottom_line:'The essential conclusion.',why_it_matters:{providers:'',patients:''},image:{src:'',caption:'',credit:'',alt:'Editorial image for this story'}});
const blankEdition=()=>({schema_version:2,edition:'003',publication_date:new Date().toISOString().slice(0,10),display_date:new Intl.DateTimeFormat('en-US',{weekday:'long',year:'numeric',month:'long',day:'numeric'}).format(new Date()),theme:'A New Edition',summary:'The connecting idea behind today’s essential stories.',reading_time:'10 minutes',editor_note:'Good morning. Here is what we are seeing today.',sections:[{name:'News',story_slugs:['new-story']}],stories:[blankStory()],radar:[{title:'A developing story',detail:'What the newsroom is watching next.'}],closing_thought:'Clarity begins with knowing what matters.'});
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),at=(o,p)=>p.split('.').reduce((v,k)=>v?.[k],o)??'';function put(o,p,v){const k=p.split('.');let x=o;k.slice(0,-1).forEach(a=>x=x[a]||(x[a]={}));x[k.at(-1)]=v}
function sourceText(items){return(items||[]).map(x=>`${x.title} | ${x.url}`).join('\n')}function sourceArray(text){return text.split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{const i=line.lastIndexOf('|');return i<0?{title:line,url:''}:{title:line.slice(0,i).trim(),url:line.slice(i+1).trim()}})}
function sync(){const data=Object.fromEntries(new FormData(form));Object.assign(model,data);model.schema_version=2;model.stories=$$('.story-editor').map(el=>{const s={why_it_matters:{},image:{}};$$('[data-field]',el).forEach(f=>{let v=f.value.trim();if(f.dataset.field==='body')v=v.split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean);if(f.dataset.field==='sources')v=sourceArray(v);put(s,f.dataset.field,v)});return s});const groups=new Map();model.stories.forEach(s=>{if(!groups.has(s.section))groups.set(s.section,[]);groups.get(s.section).push(s.slug)});model.sections=[...groups].map(([name,story_slugs])=>({name,story_slugs}));model.radar=$$('.radar-editor').map(el=>Object.fromEntries($$('[data-field]',el).map(f=>[f.dataset.field,f.value.trim()])));$('#editor-heading').textContent=`Edition ${model.edition||'—'}`;status=$('#draft-status').value;validate()}
function addEditor(type,item){const node=$(`#${type}-template`).content.firstElementChild.cloneNode(true),target=type==='story'?storiesEl:radarEl;$$('[data-field]',node).forEach(f=>f.value=f.dataset.field==='sources'?sourceText(item.sources):Array.isArray(at(item,f.dataset.field))?at(item,f.dataset.field).join('\n\n'):at(item,f.dataset.field));node.onclick=e=>{const a=e.target.dataset.action;if(!a)return;if(a==='remove')node.remove();if(a==='up'&&node.previousElementSibling)target.insertBefore(node,node.previousElementSibling);if(a==='down'&&node.nextElementSibling)target.insertBefore(node.nextElementSibling,node);queue()};target.append(node)}
function render(){['edition','publication_date','display_date','theme','summary','reading_time','editor_note','closing_thought'].forEach(k=>form.elements[k].value=model[k]||'');$('#draft-status').value=status;storiesEl.replaceChildren();model.stories.forEach(s=>addEditor('story',s));radarEl.replaceChildren();model.radar.forEach(r=>addEditor('radar',r));sync();drafts();preview()}
function validate(){lastErrors=BeaconValidator.validate(model);const box=$('#validation-summary');box.className=lastErrors.length?'validation-errors':'validation-ok';box.innerHTML=lastErrors.length?`<strong>${lastErrors.length} validation issue${lastErrors.length===1?'':'s'}</strong><ul>${lastErrors.slice(0,12).map(e=>`<li><code>${esc(e.path)}</code> ${esc(e.message)}</li>`).join('')}</ul>`:'<strong>✓ Canonical edition JSON is valid and ready for approval.</strong>';return !lastErrors.length}
function queue(){clearTimeout(timer);timer=setTimeout(()=>{sync();preview()},200)}function preview(){localStorage.setItem('beacon-preview',JSON.stringify(model));const mode=$('.devices .active')?.dataset.device||'desktop';$('#preview').src=`preview.html?mode=${mode}&v=${Date.now()}`}
function save(){sync();localStorage.setItem(`beacon-draft-${model.edition}`,JSON.stringify({status,edition:model}));$('#save-status').textContent=`Saved at ${new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`;drafts()}
function drafts(){const list=$('#draft-list'),items=Object.keys(localStorage).filter(k=>k.startsWith('beacon-draft-')).map(k=>{try{return JSON.parse(localStorage.getItem(k))}catch{return null}}).filter(Boolean);list.innerHTML=items.length?'':'<p>No drafts yet.</p>';items.forEach(d=>{const b=document.createElement('button');b.className='draft-button';b.innerHTML=`<strong>Edition ${esc(d.edition.edition)}</strong><span>${esc(d.status)} · ${esc(d.edition.theme)}</span>`;b.onclick=()=>{model=structuredClone(d.edition);status=d.status;render()};list.append(b)})}
function importJson(text){let next;try{next=JSON.parse(text)}catch(e){$('#import-feedback').textContent=`Malformed JSON: ${e.message}`;return}const errors=BeaconValidator.validate(next);if(errors.length){$('#import-feedback').innerHTML=`<strong>${errors.length} validation issue${errors.length===1?'':'s'}:</strong><ul>${errors.slice(0,10).map(e=>`<li>${esc(e.path)} — ${esc(e.message)}</li>`).join('')}</ul>`;return}model=next;status='draft';render();save();$('#import-dialog').close()}
async function readFile(file){if(!file)return;if(!/\.json$/i.test(file.name)){$('#import-feedback').textContent='Choose a .json file.';return}$('#import-text').value=await file.text();$('#import-feedback').textContent=`Loaded ${file.name}. Select Validate and import.`}
function blobDownload(){sync();if(!validate())return false;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(model,null,2)+'\n'],{type:'application/json'}));a.download=`${model.edition}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);return true}
function b64(value){const bytes=new TextEncoder().encode(value);let binary='';bytes.forEach(b=>binary+=String.fromCharCode(b));return btoa(binary)}
function preparePublish(){sync();if(!validate()){scrollTo({top:0,behavior:'smooth'});return}const payload=b64(JSON.stringify(model)),cmd=`gh workflow run publish-edition.yml --repo Jburris04/The-Beacon -f edition_json_base64='${payload}'`;$('#publish-command').innerHTML=`<p><strong>Edition ${esc(model.edition)}</strong> passed validation.</p><code>gh workflow run publish-edition.yml --repo Jburris04/The-Beacon …</code>`;$('#publish-dialog').dataset.command=cmd;$('#publish-progress').textContent='Download the JSON for the local CLI, or copy the authenticated GitHub CLI command.';$('#publish-links').replaceChildren();$('#publish-dialog').showModal()}
async function checkStatus(){const box=$('#publish-progress');box.textContent='Checking the public GitHub workflow…';try{const r=await fetch('https://api.github.com/repos/Jburris04/The-Beacon/actions/workflows/publish-edition.yml/runs?per_page=1');if(!r.ok)throw new Error(`GitHub returned ${r.status}`);const run=(await r.json()).workflow_runs[0];if(!run){box.textContent='No publishing workflow run has started yet.';return}box.textContent=`Latest run: ${run.status}${run.conclusion?` · ${run.conclusion}`:''} · commit ${run.head_sha.slice(0,7)}`;const base='https://jburris04.github.io/The-Beacon/',articles=model.stories.map(s=>`<a href="${base}article/${esc(s.slug)}/" target="_blank">${esc(s.headline)} ↗</a>`).join('');$('#publish-links').innerHTML=`<a href="${run.html_url}" target="_blank">GitHub workflow ↗</a><a href="${base}" target="_blank">Homepage ↗</a><a href="${base}edition/${model.edition}/" target="_blank">Edition ↗</a><a href="${base}archive/" target="_blank">Archive ↗</a>${articles}`}catch(e){box.textContent=`Could not read workflow status: ${e.message}`}}
form.oninput=queue;$('#draft-status').onchange=()=>{status=$('#draft-status').value;save()};$('#save-draft').onclick=save;$('#new-edition').onclick=()=>{model=blankEdition();status='draft';render()};$('#export-json').onclick=blobDownload;$('#add-story').onclick=()=>{addEditor('story',blankStory());queue()};$('#add-radar').onclick=()=>{addEditor('radar',{title:'New Radar item',detail:''});queue()};$('#import-launch').onclick=()=>$('#import-dialog').showModal();$('#parse-import').onclick=()=>importJson($('#import-text').value);$('#file-input').onchange=e=>readFile(e.target.files[0]);const drop=$('#drop-zone');['dragenter','dragover'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.add('dragging')}));['dragleave','drop'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.remove('dragging')}));drop.ondrop=e=>readFile(e.dataTransfer.files[0]);$('.devices').onclick=e=>{if(!e.target.dataset.device)return;$$('.devices button').forEach(b=>b.classList.toggle('active',b===e.target));$('.preview-stage').className=`preview-stage ${e.target.dataset.device}`;preview()};$('#publish').onclick=preparePublish;$('#download-publish').onclick=blobDownload;$('#copy-workflow').onclick=async()=>{await navigator.clipboard.writeText($('#publish-dialog').dataset.command);$('#publish-progress').textContent='Workflow command copied. Run it in an authenticated terminal.'};$('#check-status').onclick=checkStatus;
fetch('../content/editions/002.json').then(r=>r.json()).then(d=>{model=d;status='published';render()}).catch(()=>{model=blankEdition();render()});
