const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const form=$('#edition-form'),storiesEl=$('#story-editors'),radarEl=$('#radar-editors');let model,previewTimer;
const blankStory=()=>({slug:'new-story',section:'News',headline:'Untitled story',standfirst:'What readers need to know.',paragraphs:['Begin the story here.'],pull_quote:'',bottom_line:'',provider_impact:'',patient_impact:'',image:{src:'',alt:'',caption:'',credit:''}});
const blankEdition=()=>({schema_version:1,status:'draft',edition:'003',date:new Date().toISOString().slice(0,10),date_display:'',theme:'A New Edition',summary:'The connecting idea behind today’s essential stories.',editor_note:'Good morning. Here is what we are seeing today.',reading_time:'',stories:[blankStory()],radar:[{title:'A developing story',detail:'What the newsroom is watching next.'}]});
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function valueAt(o,path){return path.split('.').reduce((v,k)=>v?.[k],o)??''}function setAt(o,path,value){const keys=path.split('.');let p=o;keys.slice(0,-1).forEach(k=>p=p[k]||(p[k]={}));p[keys.at(-1)]=value}
function sync(){const data=Object.fromEntries(new FormData(form));Object.assign(model,data);model.date_display=new Intl.DateTimeFormat('en-US',{weekday:'long',year:'numeric',month:'long',day:'numeric'}).format(new Date(`${model.date}T12:00:00`));model.stories=$$('.story-editor',storiesEl).map(el=>{const o={image:{}};$$('[data-field]',el).forEach(f=>setAt(o,f.dataset.field,f.dataset.field==='paragraphs'?f.value.split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean):f.value.trim()));return o});model.radar=$$('.radar-editor',radarEl).map(el=>{const o={};$$('[data-field]',el).forEach(f=>o[f.dataset.field]=f.value.trim());return o});if(!model.reading_time)model.reading_time=BeaconParser.readingTime(model.stories);$('#editor-heading').textContent=`Edition ${model.edition||'—'}`}
function addEditor(type,item){const template=$(`#${type}-template`),node=template.content.firstElementChild.cloneNode(true),target=type==='story'?storiesEl:radarEl;$$('[data-field]',node).forEach(f=>{let v=valueAt(item,f.dataset.field);if(Array.isArray(v))v=v.join('\n\n');f.value=v});node.addEventListener('click',e=>{const action=e.target.dataset.action;if(!action)return;if(action==='remove')node.remove();if(action==='up'&&node.previousElementSibling)target.insertBefore(node,node.previousElementSibling);if(action==='down'&&node.nextElementSibling)target.insertBefore(node.nextElementSibling,node);queuePreview()});target.append(node)}
function render(){['edition','date','theme','summary','editor_note','reading_time','status'].forEach(k=>form.elements[k].value=model[k]||'');storiesEl.replaceChildren();model.stories.forEach(s=>addEditor('story',s));radarEl.replaceChildren();model.radar.forEach(r=>addEditor('radar',r));sync();renderDrafts();updatePreview()}
function drafts(){return Object.keys(localStorage).filter(k=>k.startsWith('beacon-draft-')).map(k=>JSON.parse(localStorage.getItem(k))).sort((a,b)=>b.date.localeCompare(a.date))}
function renderDrafts(){const list=$('#draft-list'),ds=drafts();list.innerHTML=ds.length?'':'<p>No editions saved yet.</p>';ds.forEach(d=>{const b=document.createElement('button');b.className='draft-button';b.innerHTML=`<strong>Edition ${esc(d.edition)}</strong><span><i class="status-dot"></i>${esc(d.status||'draft')} · ${esc(d.theme)}</span>`;b.onclick=()=>{model=structuredClone(d);render()};list.append(b)})}
function save(status){sync();if(status)model.status=status;localStorage.setItem(`beacon-draft-${model.edition}`,JSON.stringify(model));$('#save-status').textContent=`Saved at ${new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`;renderDrafts()}
function queuePreview(){clearTimeout(previewTimer);previewTimer=setTimeout(updatePreview,220)}function updatePreview(){sync();localStorage.setItem('beacon-preview',JSON.stringify(model));const frame=$('#preview'),mode=$('.devices .active')?.dataset.device||'desktop';frame.src=`preview.html?mode=${mode}&v=${Date.now()}`}
function importText(text){try{const parsed=BeaconParser.parse(text);model=parsed.edition;render();save();$('#import-feedback').innerHTML=parsed.warnings.length?`Imported with ${parsed.warnings.length} note${parsed.warnings.length===1?'':'s'}: ${parsed.warnings.map(esc).join(' ')}`:'Edition recognized. All core fields are ready.';setTimeout(()=>$('#import-dialog').close(),500)}catch(e){$('#import-feedback').textContent=e.message}}
async function fileImport(file){if(!file)return;if(!/\.(md|markdown|txt)$/i.test(file.name)&&!/^text\//.test(file.type)){$('#import-feedback').textContent='Choose a Markdown or text file.';return}$('#import-text').value=await file.text();$('#import-feedback').textContent=`Loaded ${file.name}. Select Import to continue.`}
function exportJson(){sync();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(model,null,2)+'\n'],{type:'application/json'}));a.download=`edition-${model.edition}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function showGithub(){const c=BeaconGitHub.config();$('#github-owner').value=c.owner;$('#github-repo').value=c.repo;$('#github-branch').value=c.branch;$('#github-token').value='';$('#github-dialog').showModal()}
async function publish(){sync();const warnings=BeaconParser.validate(model);if(warnings.length&&!confirm(`${warnings.join('\n')}\n\nPublish anyway?`))return;if(!BeaconGitHub.connected()){showGithub();return}const dlg=$('#publish-dialog'),progress=$('#publish-progress');$('#publish-title').textContent='Preparing your release…';$('#publish-label').textContent=`Edition ${model.edition}`;$('#publish-links').replaceChildren();$('.publish-result',dlg).classList.remove('success');dlg.showModal();try{const getJson=(u,fallback)=>fetch(u,{cache:'no-store'}).then(r=>r.ok?r.json():fallback).catch(()=>fallback),[index,search,related,sitemap]=await Promise.all([getJson('../content/editions/index.json',[]),getJson('../content/search-index.json',[]),getJson('../content/related.json',{}),fetch('../sitemap.xml',{cache:'no-store'}).then(r=>r.ok?r.text():'').catch(()=>'')]);const generated=await BeaconGenerator.build(model,index,search,related,sitemap);const release=await BeaconGitHub.publish(generated.files,`Publish Beacon Edition ${model.edition}: ${model.theme}`,m=>progress.textContent=m);progress.textContent='GitHub accepted the release.';await BeaconGitHub.waitForPages(model.edition,90000,m=>progress.textContent=m);model=generated.edition;save('published');$('.publish-result',dlg).classList.add('success');$('#publish-mark').textContent='✓';$('#publish-title').textContent='Edition Published';progress.textContent='The live Beacon has been updated.';const links=[['Homepage',generated.links.homepage],['Edition',generated.links.edition],['Archive',generated.links.archive],...generated.links.articles.map(x=>[x.title,x.url]),['GitHub commit',release.html_url]];$('#publish-links').innerHTML=links.map(([t,u])=>`<a href="${esc(u)}" target="_blank"><span>${esc(t)}</span><span>↗</span></a>`).join('')}catch(e){$('#publish-mark').textContent='!';$('#publish-title').textContent='Publish needs attention';progress.textContent=e.message}}
async function showHistory(){if(!BeaconGitHub.connected()){showGithub();return}const dlg=$('#history-dialog'),list=$('#history-list');list.innerHTML='<p>Loading published releases…</p>';dlg.showModal();try{const commits=await BeaconGitHub.history();list.innerHTML=commits.map(c=>`<article class="history-item"><div><strong>${esc(c.commit.message)}</strong><p>${new Date(c.commit.author.date).toLocaleString()} · ${c.sha.slice(0,7)}</p></div><button data-sha="${c.sha}">Roll back</button></article>`).join('')||'<p>No publication history found.</p>'}catch(e){list.textContent=e.message}}
form.addEventListener('input',queuePreview);$('#save-draft').onclick=()=>save();$('#export-json').onclick=exportJson;$('#new-edition').onclick=()=>{model=blankEdition();render()};$('#add-story').onclick=()=>{addEditor('story',blankStory());queuePreview()};$('#add-radar').onclick=()=>{addEditor('radar',{title:'New Radar item',detail:''});queuePreview()};
$('#import-launch').onclick=()=>$('#import-dialog').showModal();$('#parse-import').onclick=()=>importText($('#import-text').value);$('#file-input').onchange=e=>fileImport(e.target.files[0]);const drop=$('#drop-zone');['dragenter','dragover'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.add('dragging')}));['dragleave','drop'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.remove('dragging')}));drop.addEventListener('drop',e=>fileImport(e.dataTransfer.files[0]));
$('.devices').onclick=e=>{if(!e.target.dataset.device)return;$$('.devices button').forEach(b=>b.classList.toggle('active',b===e.target));const stage=$('.preview-stage');stage.className=`preview-stage ${e.target.dataset.device}`;updatePreview()};
$('#github-settings').onclick=showGithub;$('#save-github').onclick=()=>{BeaconGitHub.configure({owner:$('#github-owner').value.trim(),repo:$('#github-repo').value.trim(),branch:$('#github-branch').value.trim()},$('#github-token').value);$('#github-dialog').close();$('#save-status').textContent='GitHub connected for this session.'};$('#publish').onclick=publish;$('#close-publish').onclick=()=>$('#publish-dialog').close();$('#history-launch').onclick=showHistory;$('#history-list').onclick=async e=>{const sha=e.target.dataset.sha;if(!sha)return;if(!confirm(`Roll the entire public site back to ${sha.slice(0,7)}? A new rollback commit will preserve the current history.`))return;e.target.disabled=true;e.target.textContent='Rolling back…';try{await BeaconGitHub.rollback(sha,m=>e.target.textContent=m);e.target.textContent='Rollback published';setTimeout(()=>$('#history-dialog').close(),900)}catch(err){e.target.disabled=false;e.target.textContent=err.message}};
fetch('../content/editions/edition-002.json').then(r=>r.json()).then(d=>{model=d;model.status=model.status||'published';model.stories.forEach(s=>s.image=s.image||{src:'',alt:'',caption:'',credit:''});render()}).catch(()=>{model=blankEdition();render()});
