import fs from 'node:fs/promises';import path from 'node:path';
const origin='https://jburris04.github.io/The-Beacon/';
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const readJson=async(file,fallback)=>{try{return JSON.parse(await fs.readFile(file,'utf8'))}catch{return fallback}};
const shell=(kind,id,title,description)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} — The Beacon</title><meta name="description" content="${esc(description)}"><link rel="stylesheet" href="../../assets/styles.css"></head><body data-view="${kind}" data-${kind==='article'?'slug':'edition'}="${esc(id)}" data-base="../../"><div class="topline"></div><header class="masthead"><div class="masthead-inner"><nav class="site-nav"><a href="../../index.html">Home</a><a href="../../archive/index.html">Editions</a><a href="../../about/index.html">About</a></nav><a class="wordmark" href="../../index.html">THE BEACON<small>CLARITY WITHOUT THE NOISE</small></a><div class="nav-actions"><button class="theme-toggle" aria-label="Switch color theme"></button><a class="subscribe-link" href="../../subscribe/index.html">Subscribe</a><button class="menu-button">Menu</button></div></div></header>${kind==='article'?'<main class="article-page shell"><article><a class="back-link" id="article-back"></a><header class="article-header"><p class="eyebrow" id="article-section"></p><h1 id="article-headline">Loading story…</h1><p class="standfirst" id="article-standfirst"></p><p class="byline" id="article-byline"></p></header><div class="article-body" id="article-body"></div></article><aside class="article-aside"><p class="eyebrow">This Edition</p><h2 id="article-theme"></h2><a class="text-link" id="article-theme-link">Read the full edition →</a></aside></main>':'<main><header class="edition-hero shell"><p class="eyebrow"><span id="edition-number"></span> · <span id="edition-date"></span></p><h1 id="edition-theme">Loading…</h1><p class="hero-summary" id="edition-summary"></p><div class="edition-meta"><span id="reading-time"></span><button class="print-button">Print this edition</button></div></header><section class="editor-note shell"><p class="eyebrow">From the Editorial Desk</p><h2>Good morning.</h2><p id="editor-note"></p></section><section class="edition-stories shell" id="edition-stories"></section><div id="edition-radar"></div></main>'}<script src="../../assets/site.js"></script></body></html>`;

export async function buildArtifacts(edition,repoRoot,{allowUpdate=false}={}){
  const contentDir=path.join(repoRoot,'content'),editionDir=path.join(contentDir,'editions');
  const index=await readJson(path.join(editionDir,'index.json'),[]);const exists=index.some(x=>x.edition===edition.edition);if(exists&&!allowUpdate)throw new Error(`Edition ${edition.edition} already exists. Use --update only when intentionally replacing it.`);
  const summary={edition:edition.edition,publication_date:edition.publication_date,display_date:edition.display_date,theme:edition.theme,summary:edition.summary,reading_time:edition.reading_time};
  const nextIndex=[summary,...index.filter(x=>x.edition!==edition.edition)].sort((a,b)=>b.publication_date.localeCompare(a.publication_date));
  const oldSearch=await readJson(path.join(contentDir,'search-index.json'),[]);const search=[...edition.stories.map(s=>({edition:edition.edition,publication_date:edition.publication_date,slug:s.slug,section:s.section,category:s.category,headline:s.headline,standfirst:s.standfirst,url:`article/${s.slug}/index.html`})),...oldSearch.filter(s=>s.edition!==edition.edition)];
  const oldRelated=await readJson(path.join(contentDir,'related.json'),{}),related={...oldRelated};for(const s of edition.stories)related[s.slug]=edition.stories.filter(x=>x.slug!==s.slug).sort((a,b)=>(b.section===s.section)-(a.section===s.section)).slice(0,3).map(x=>x.slug);
  const files=new Map();files.set(`content/editions/${edition.edition}.json`,JSON.stringify(edition,null,2)+'\n');files.set('content/editions/index.json',JSON.stringify(nextIndex,null,2)+'\n');files.set('content/search-index.json',JSON.stringify(search,null,2)+'\n');files.set('content/related.json',JSON.stringify(related,null,2)+'\n');files.set(`edition/${edition.edition}/index.html`,shell('edition',edition.edition,`Edition ${edition.edition}: ${edition.theme}`,edition.summary));for(const s of edition.stories)files.set(`article/${s.slug}/index.html`,shell('article',s.slug,s.headline,s.standfirst));
  files.set('rss.xml',rss(nextIndex));files.set('sitemap.xml',sitemap(nextIndex,search));return {files,index:nextIndex,search,related,exists};
}
function rss(index){return `<?xml version="1.0" encoding="UTF-8"?>\n<rss version="2.0"><channel><title>The Beacon</title><link>${origin}</link><description>Clarity without the noise.</description>${index.map(e=>`<item><title>${esc(e.theme)}</title><link>${origin}edition/${e.edition}/</link><guid>${origin}edition/${e.edition}/</guid><pubDate>${new Date(`${e.publication_date}T12:00:00Z`).toUTCString()}</pubDate><description>${esc(e.summary)}</description></item>`).join('')}</channel></rss>\n`}
function sitemap(index,search){const urls=new Set([origin,`${origin}archive/`,`${origin}about/`,`${origin}subscribe/`]);index.forEach(e=>urls.add(`${origin}edition/${e.edition}/`));search.forEach(s=>urls.add(`${origin}${s.url.replace(/index\.html$/,'')}`));return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${[...urls].map(u=>`<url><loc>${esc(u)}</loc></url>`).join('')}</urlset>\n`}
export async function writeArtifacts(repoRoot,artifacts){for(const [relative,content] of artifacts.files){const file=path.join(repoRoot,relative);await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,content)}}
export function liveLinks(edition){return {homepage:origin,edition:`${origin}edition/${edition.edition}/`,archive:`${origin}archive/`,articles:edition.stories.map(s=>({headline:s.headline,url:`${origin}article/${s.slug}/`}))}}
